# =============================================================================
# 02_add_edge_data.R
# Load, validate and export commuting / flow (edge) data
#
# Required input schema (flows_df):
#   origin_id      : character  — must match IDs in the relevant spatial layer
#   destination_id : character  — must match IDs in the relevant spatial layer
#   flow_value     : numeric    — number of commuters / trips
#   variable_name  : character  — e.g. "commuters_2024"
#   year           : integer    — e.g. 2024
#
# Outputs written to app-development/static/data/:
#   flows.parquet         — full validated flows
#   flow_summary.parquet  — per-origin totals
# =============================================================================
source("R_scripts/preparing_data/utils.R")
library(arrow)
library(dplyr)
# ── Config ────────────────────────────────────────────────────────────────────
STATIC_DATA_DIR <- "app-development/static/data"
SAMPLE_DATA_DIR <- "data/sample"
# ── Load data ─────────────────────────────────────────────────────────────────
# Replace this with your actual data path when the restricted dataset arrives.
# For now, uses the toy sample generated by generate_sample_data.R
flows_raw <- read.csv(file.path(SAMPLE_DATA_DIR, "commuting_rijnmond_mini.csv"),
                      stringsAsFactors = FALSE)
# ── Validate ──────────────────────────────────────────────────────────────────
flows_validated <- validate_flows(flows_raw, label = "commuting_2024")
# ── Summarise per origin ──────────────────────────────────────────────────────
flow_summary <- flows_validated |>
  group_by(origin_id) |>
  summarise(
    total_outflow  = sum(flow_value, na.rm = TRUE),
    n_destinations = n_distinct(destination_id),
    .groups = "drop"
  )
# ── Export ────────────────────────────────────────────────────────────────────
if (!dir.exists(STATIC_DATA_DIR)) dir.create(STATIC_DATA_DIR, recursive = TRUE)
arrow::write_parquet(flows_validated, file.path(STATIC_DATA_DIR, "flows.parquet"))
arrow::write_parquet(flow_summary,    file.path(STATIC_DATA_DIR, "flow_summary.parquet"))
message("✓ Edge data exported to ", STATIC_DATA_DIR)
